### ISSUE TITLE
Broken specs with latest update

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-plugin-lutaml#107]
Someone has released an update to this gem, without bothering to check what he has broken in rspec

https://github.com/metanorma/metanorma-plugin-lutaml/actions/runs/8804720741/job/24165706968

and the update is now breaking standoc as well. This is an update that is required for an external client in https://github.com/metanorma/iso-10303-srl/issues/72

The fact that this is a minor version change, and therefore would not automatically impact the Metanorma chain, is irrelevant. Metanorma gems must not be released unless tested, and it is the responsibility of the person making the change to make sure that the tests are updated.

If you cannot release gems in a responsible fashion, do  not release gems at all. It is not my responsibility to fix other people's negligence.

**Comment by opoudjis** [comment]
Issue appears to be forgetting to insert measure_schemaexpg5.svg in spec, but I am getting a lot of Liquid errors in standoc, so I am not convinced that's all that's going on.

**Comment by opoudjis** [comment]
This was last working at https://github.com/metanorma/metanorma-plugin-lutaml/commit/c56ebaadd75c5744ae6472bfd86f8eb42376e116 a month ago. I have reverted to that version and reverted expressir, and it still is giving me Liquid render error: Liquid error: internal everywhere.

The breakages from https://github.com/metanorma/metanorma-plugin-lutaml/actions/runs/8796923216/job/24145754850 were because of vectory 0.7.4. The breakages I am getting are with vectory 0.7.5, and they are Liquid errors, not vectory errors. Trying to work out if they are restricted to SVG processing.

**Comment by opoudjis** [comment]
This is fucking bullshit.

````
(ruby) node.render_to_output_buffer(context, output)
eval error: can't modify frozen String: ""
  /Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/reverse_adoc-1.0.0/lib/reverse_adoc/cleaner.rb:21:in `gsub!'
  /Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/reverse_adoc-1.0.0/lib/reverse_adoc/cleaner.rb:21:in `remove_inner_whitespaces'
  /Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/reverse_adoc-1.0.0/lib/reverse_adoc/cleaner.rb:4:in `tidy'
  /Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/reverse_adoc-1.0.0/lib/reverse_adoc/html_converter.rb:58:in `convert'
  /Users/nickn/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/reverse_adoc-1.0.0/lib/reverse_adoc.rb:15:in `convert'
  /Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-plugin-lutaml/lib/metanorma/plugin/lutaml/liquid/custom_filters.rb:9:in `html2adoc'
````

@ronaldtse you are:

* releasing upgrades to reverse_adoc with no release notes
* that are resulting in breaking downstream gems
* with no warning

This is wasting Metanorma users time as well as mine. I have spent 1.5 hrs on this so far that was supposed to be spent on ISO-10303.

**Comment by opoudjis** [comment]
Not to mention that your code change in reverse_adoc is removing the necessary `:stem:` document attribute from the start of generated documents, and for reasons I cannot fathom, GHA did not pick this up.

**Comment by opoudjis** [comment]
I am now having to fix some other issue in this gem because whatever was done in coradoc, this:

````
The attribute &quot;uniformResourceIdentifier&quot;&lt;i&gt; &lt;/i&gt;takes
````

is now skipping the space after coradoc integration, and is rendering as:

````
<p id="_">The attribute “uniformResourceIdentifier”takes as its value a set of URI’s
````

@webdev778 The updates you are doing are disrupting my code stack, because they are being released before sufficient testing, and because dependencies that were not being version-restricted before are now coming to bite me. It may be my fault for not putting in version-restriction on those gems five years ago. 


But this is going to stop now. I am debugging this instance, but it is the last such that I am debugging.  I have spent two hours on one gem trying to track errors your release has introduced into external gem testing, and that is not my job.

I am going to put a restriction on my codestack to only use reverse_adoc 0.3.x, effective immediately after I fix this new bug. If I don't get this new issue resolved quickly, I'm going to throw that back to you to fix, too.

I will not relax that restriction until all gems dependent on reverse_adoc have been tested for impact.

That testing is not my responsibility. It is yours.

As perusal of https://github.com/search?q=org%3Ametanorma%20reverse_adoc&type=code will indicate, the gems impacted are:

* https://github.com/metanorma/stepmod-utils
* https://github.com/metanorma/bipm-data-importer
* https://github.com/metanorma/metanorma-plugin-lutaml

**Comment by opoudjis** [comment]
Issue identified in https://github.com/metanorma/reverse_adoc/issues/93

**Comment by opoudjis** [comment]
Restricting reverse_adoc dependency to 0.3.x.
