### ISSUE TITLE
Images getting invalid path from annotated source

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-plugin-lutaml#97]
*Transferred from https://github.com/metanorma/iso-10303-detached-docs/issues/110*
*In relation to https://github.com/metanorma/iso-10303-detached-docs/issues/79*

`image::` macro doesn't work properly in annotated source.

For example, the markup:
````
image::fig02.png[]
````
Causes a compilation error:
````
Invalid argument @ rb_sysopen - D:/Trabajo/Metanorma/iso-10303-detached-docs/data/documents/iso-10303-52/images/D:/Trabajo/Metanorma/iso-10303-detached-docs/data/resources/mesh_topology_schema/fig02.png
C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/image_size-3.0.1/lib/image_size/reader.rb:18:in `initialize'
C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/image_size-3.0.1/lib/image_size/reader.rb:18:in `open'
C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/image_size-3.0.1/lib/image_size/reader.rb:18:in `open'
...
````

**Comment by manuelfuenmayor** [comment]
This issue is solved by moving the image to the schema location. Closing.
